export const searchResults = [
    "Cat",
    "Cat • Male",
    "Cat • Female",
    "Cat • Baby",
    "Cat • Young",
    "Cat • Adult",
    "Cat • Senior",
    "Cat • Small",
    "Cat • Medium",
    "Cat • Large",
    "Cat • Extra Large",
    "Dog",
    "Dog • Male",
    "Dog • Female",
    "Dog • Baby",
    "Dog • Young",
    "Dog • Adult",
    "Dog • Senior",
    "Dog • Small",
    "Dog • Medium",
    "Dog • Large",
    "Dog • Extra Large",
    "Rabbit",
    "Rabbit • Male",
    "Rabbit • Female",
    "Rabbit • Baby",
    "Rabbit • Young",
    "Rabbit • Adult",
    "Rabbit • Senior",
    "Rabbit • Small",
    "Rabbit • Medium",
    "Rabbit • Large",
    "Rabbit • Extra Large",
    "Horse",
    "Horse • Male",
    "Horse • Female",
    "Horse • Baby",
    "Horse • Young",
    "Horse • Adult",
    "Horse • Senior",
    "Horse • Small",
    "Horse • Medium",
    "Horse • Large",
    "Horse • Extra Large",
    "Bird",
    "Bird • Male",
    "Bird • Female",
    "Bird • Baby",
    "Bird • Young",
    "Bird • Adult",
    "Bird • Senior",
    "Bird • Small",
    "Bird • Medium",
    "Bird • Large",
    "Bird • Extra Large",
    "Scales, Fins, & Other",
    "Scales, Fins, & Other • Male",
    "Scales, Fins, & Other • Female",
    "Scales, Fins, & Other • Baby",
    "Scales, Fins, & Other • Young",
    "Scales, Fins, & Other • Adult",
    "Scales, Fins, & Other • Senior",
    "Scales, Fins, & Other • Small",
    "Scales, Fins, & Other • Medium",
    "Scales, Fins, & Other • Large",
    "Scales, Fins, & Other • Extra Large",
    // "Barnyard",
    // "Barnyard • Male",
    // "Barnyard • Female",
    // "Barnyard • Baby",
    // "Barnyard • Young",
    // "Barnyard • Adult",
    // "Barnyard • Senior",
    // "Barnyard • Small",
    // "Barnyard • Medium",
    // "Barnyard • Large",
    // "Barnyard • Extra Large"
]
