"""create users table

Revision ID: e720f8caddd0
Revises:
Create Date: 2023-06-13 17:29:53.054186

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'e720f8caddd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('firstName', sa.String(length=30), nullable=True),
    sa.Column('lastName', sa.String(length=30), nullable=True),
    sa.Column('zipCode', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('adoptionAgency', sa.Boolean(), nullable=False),
    sa.Column('orgName', sa.String(length=255), nullable=True),
    sa.Column('desiredPet', sa.String(), nullable=True),
    sa.Column('petOwner', sa.String(), nullable=True),
    sa.Column('kids', sa.Boolean(), nullable=True),
    sa.Column('ownerType', sa.String(), nullable=True),
    sa.Column('currentPets', sa.String(), nullable=True),
    sa.Column('agePref', sa.String(), nullable=True),
    sa.Column('genderPref', sa.String(), nullable=True),
    sa.Column('sizePref', sa.String(), nullable=True),
    sa.Column('specialNeeds', sa.Boolean(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('coatLengthPref', sa.String(), nullable=True),
    sa.Column('privateOutdoor', sa.String(), nullable=True),
    sa.Column('sharedOutdoor', sa.String(), nullable=True),
    sa.Column('leaseRestriction', sa.Boolean(), nullable=True),
    sa.Column('breedRestriction', sa.String(), nullable=True),
    sa.Column('sizeRestriction', sa.Integer(), nullable=True),
    sa.Column('activityLevelPref', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
